substitutions:
    _IMAGE_NAME: 'chatbot'
    _CLOUDRUN_SERVICE_NAME: 'chatbot-service'
    _REGION: 'europe-west1'

steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build', '-t',
        'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 'deploy', '${_CLOUDRUN_SERVICE_NAME}',
        '--image', 'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated'
    ]
